### ISSUE TITLE
throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'Function');

### ISSUE THREAD

**Issue by zul00** [slashdotdash/node-ledger-web#14] opened 2018-01-09 08:28 UTC
Hi,
I tried to run it on a linux machine.
node --version v9.3.0
npm --version v5.6.0
bower --version v1.8.2
grunt-cli --version v.1.2.0

I already installed all the requrement and I run "node app.js". However I got 
the following error

> util.js:944
>    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'Function');
>    ^
>
>TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function
>    at Object.inherits (util.js:944:11)
>    at Object.<anonymous> (/home/zul/Dropbox/Project/node-ledger-web/node_modules/spdy/lib/spdy/connection.js:81:6)
>    at Module._compile (module.js:660:30)
>    at Object.Module._extensions..js (module.js:671:10)
>    at Module.load (module.js:573:32)
>    at tryModuleLoad (module.js:513:12)
>    at Function.Module._load (module.js:505:3)
>    at Module.require (module.js:604:17)
>    at require (internal/module.js:11:18)
>    at Object.<anonymous> (/home/zul/Dropbox/Project/node-ledger-web/node_modules/spdy/lib/spdy.js:20:19)

Any idea about the error?

Best Regards,
Zul

**Comment by slashdotdash** [comment] 2018-01-09 09:23
@zul00 Workaround for you is to use [nvm](https://github.com/creationix/nvm) to install and use an earlier version of Node that is known to work:

```
nvm install v4.1.0
nvm use v4.1.0
```

Happy to accept a pull request if you are able to get it working with latest Node.js. Closing this issue as it is a duplicate of #10.

**Closed as completed by slashdotdash** 2018-01-09 09:23 UTC

**Comment by MartyLake** [comment] 2019-02-03 23:56
Got this error today. maybe this should be put into the README ?
